---
# Name of the ELB
prototype_elb_name: "{{ vpc_name }}-service"

# ELB listeners
prototype_elb_listeners:
 - protocol: http
   load_balancer_port: 80
   instance_protocol: http
   instance_port: 80

# ELB health check definitions
prototype_elb_health_check:
  ping_protocol: "tcp"
  ping_port: 80
  response_timeout: 10
  interval: 30
  unhealthy_threshold: 2
  healthy_threshold: 10

# Region in which to create the ELBs
prototype_elb_region: "{{ region }}"
